-- MySQL Script generated by MySQL Workbench
-- Sun Oct 11 16:44:33 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema taobao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taobao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taobao` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `taobao` ;

-- -----------------------------------------------------
-- Table `taobao`.`buy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taobao`.`buy` ;

CREATE TABLE IF NOT EXISTS `taobao`.`buy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL COMMENT '产品ID',
  `product_name` VARCHAR(45) NOT NULL COMMENT '产品名称',
  `buy_type` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '订单类型\n0:直邮\n1:转运',
  `unit_price` INT NOT NULL COMMENT '商品单价RMB(单位:分)',
  `unit_shipping` INT NOT NULL COMMENT '单个商品运费RMB(单位:分)',
  `quantity` INT NOT NULL COMMENT '购买数量',
  `total` INT NOT NULL COMMENT '购买总花费RMB(单位:分)\n(unit_price+unit_shipping)*quantity',
  `unit_cost` INT NOT NULL COMMENT '商品成本价RMB(单位:分)\nunit_price+unit_shipping',
  `track_status` CHAR(1) NOT NULL COMMENT '物流状态\n\n0:已提交亚马逊订单\n1:亚马逊已发货\n2:转运仓库已收货\n3:转运仓库已发货\n4:本人已收货\n',
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '0:失效\n1:有效',
  `create_time` DATETIME NULL COMMENT '	',
  `update_time` DATETIME NULL,
  `update_user` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taobao`.`sell`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taobao`.`sell` ;

CREATE TABLE IF NOT EXISTS `taobao`.`sell` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL COMMENT '商品ID',
  `product_name` VARCHAR(45) NOT NULL COMMENT '商品名称',
  `unit_price` INT NOT NULL COMMENT '商品单价RMB(单位:分)',
  `unit_shipping` INT NOT NULL COMMENT '商品运费RMB(单位:分)',
  `quantity` INT NOT NULL DEFAULT 1 COMMENT '数量',
  `total` INT NOT NULL COMMENT '总价RMB(单位:分)',
  `profit` INT NOT NULL COMMENT '利润RMB(单位:分)',
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '0:失效\n1:有效',
  `create_time` DATETIME NULL COMMENT '	',
  `update_time` DATETIME NULL,
  `update_user` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taobao`.`stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taobao`.`stock` ;

CREATE TABLE IF NOT EXISTS `taobao`.`stock` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL COMMENT '商品ID',
  `product_name` VARCHAR(45) NOT NULL COMMENT '商品名称',
  `stock` INT NOT NULL COMMENT '库存数量',
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '0:失效\n1:有效',
  `create_time` DATETIME NULL COMMENT '	',
  `update_time` DATETIME NULL,
  `update_user` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taobao`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taobao`.`product` ;

CREATE TABLE IF NOT EXISTS `taobao`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL COMMENT '商品ID',
  `product_name` VARCHAR(45) NOT NULL COMMENT '商品名称',
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '0:失效\n1:有效',
  `create_time` DATETIME NULL COMMENT '	',
  `update_time` DATETIME NULL,
  `update_user` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_buy_idx` (`product_id` ASC),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC),
  CONSTRAINT `fk_product_buy`
    FOREIGN KEY (`product_id`)
    REFERENCES `taobao`.`buy` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_stock1`
    FOREIGN KEY (`product_id`)
    REFERENCES `taobao`.`stock` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_sell1`
    FOREIGN KEY (`product_id`)
    REFERENCES `taobao`.`sell` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
